import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <main
      style={{
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Head>
        <title>Calendoors</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fake-logo.png" />
      </Head>

      <section>
        <div>
          <h1>Welcome to Calendoors!</h1>
        </div>
        <div>
          <button>login</button>
        </div>
      </section>
      <section>
        <div>
          <figure>
            <Image
              src="https://placekitten.com/200/300"
              width="200"
              height="200"
              alt="cat photo"
            />
          </figure>
        </div>
        <div>
          <p>
            Ryloth was a planet in the Ryloth system of the Outer Rim
            Territories, and the homeworld of the Twi&apos;lek species. Its
            terrain varied, filled with jungles, mesas, valleys, and volcanoes,
            and had an atmosphere breathable for Twi&apos;leks and humans alike.
            A forest covered its equator, filled with dangerous predators. Given
            the varied and dangerous terrain, Twi&apos;leks lived in caves
            underground where it was safer.
          </p>
          <nav>
            <button>see demo</button>
            <button>get started</button>
          </nav>
        </div>
      </section>
      <section>
        <nav>
          <a
            href="https://github.com/sgerpdx/calendoors"
            target="_blank"
            rel="noreferrer"
          >
            github
          </a>
        </nav>
      </section>
    </main>
  );
}
