import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <h1>Welcome to Calendoors!</h1>
        <button>sign up</button>
        <figure>
          <Image
            src="https://placekitten.com/200/300"
            width="200"
            height="200"
            alt="cat photo"
          />
        </figure>
        <textarea placeholder="user info displays here" />
      </section>
    </div>
  );
}
